### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。

### ISSUE THREAD

**Issue by maybe-why-not** [ice-doom/codeql_compile#2]
```
E:\codeql\codeql_compile
λ python3 codeql_compile.py -a D:\infiles -o D:\infiles_save_1643827355 -c
Traceback (most recent call last):
  File "E:\codeql\codeql_compile\codeql_compile.py", line 127, in <module>
    check()
  File "E:\codeql\codeql_compile\codeql_compile.py", line 70, in check
    shutil.rmtree(save_path + "/procyon_class")
  File "E:\Python39\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\Python39\lib\shutil.py", line 596, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "E:\Python39\lib\shutil.py", line 593, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\infiles_save_1643827355/procyon_class'
```

**Comment by ice-doom** [comment]
可以先不用校验那个步骤，第一步反编译目前来说够用了
